/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_poreid_macosx_smartcardio_PlatformPCSC */

#ifndef _Included_org_poreid_macosx_smartcardio_PlatformPCSC
#define _Included_org_poreid_macosx_smartcardio_PlatformPCSC
#ifdef __cplusplus
extern "C" {
#endif
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_T0
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_T0 1L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_T1
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_T1 2L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_RAW
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PROTOCOL_RAW 4L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_UNKNOWN
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_UNKNOWN 1L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_ABSENT
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_ABSENT 2L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PRESENT
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_PRESENT 4L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_SWALLOWED
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_SWALLOWED 8L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_POWERED
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_POWERED 16L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_NEGOTIABLE
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_NEGOTIABLE 32L
#undef org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_SPECIFIC
#define org_poreid_macosx_smartcardio_PlatformPCSC_SCARD_SPECIFIC 64L
/*
 * Class:     org_poreid_macosx_smartcardio_PlatformPCSC
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_poreid_macosx_smartcardio_PlatformPCSC_initialize
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
