/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_poreid_macosx_smartcardio_PCSC */

#ifndef _Included_org_poreid_macosx_smartcardio_PCSC
#define _Included_org_poreid_macosx_smartcardio_PCSC
#ifdef __cplusplus
extern "C" {
#endif
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_T0
#define org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_T0 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_T1
#define org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_T1 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_RAW
#define org_poreid_macosx_smartcardio_PCSC_SCARD_PROTOCOL_RAW 4L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_UNKNOWN
#define org_poreid_macosx_smartcardio_PCSC_SCARD_UNKNOWN 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_ABSENT
#define org_poreid_macosx_smartcardio_PCSC_SCARD_ABSENT 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_PRESENT
#define org_poreid_macosx_smartcardio_PCSC_SCARD_PRESENT 4L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SWALLOWED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SWALLOWED 8L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_POWERED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_POWERED 16L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_NEGOTIABLE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_NEGOTIABLE 32L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SPECIFIC
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SPECIFIC 64L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_S_SUCCESS
#define org_poreid_macosx_smartcardio_PCSC_SCARD_S_SUCCESS 0L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_CANCELLED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_CANCELLED -2146435070L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_CANT_DISPOSE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_CANT_DISPOSE -2146435058L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INSUFFICIENT_BUFFER
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INSUFFICIENT_BUFFER -2146435064L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_ATR
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_ATR -2146435051L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_HANDLE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_HANDLE -2146435069L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_PARAMETER
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_PARAMETER -2146435068L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_TARGET
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_TARGET -2146435067L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_VALUE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_INVALID_VALUE -2146435055L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_MEMORY
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_MEMORY -2146435066L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_F_COMM_ERROR
#define org_poreid_macosx_smartcardio_PCSC_SCARD_F_COMM_ERROR -2146435053L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_F_INTERNAL_ERROR
#define org_poreid_macosx_smartcardio_PCSC_SCARD_F_INTERNAL_ERROR -2146435071L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_F_UNKNOWN_ERROR
#define org_poreid_macosx_smartcardio_PCSC_SCARD_F_UNKNOWN_ERROR -2146435052L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_F_WAITED_TOO_LONG
#define org_poreid_macosx_smartcardio_PCSC_SCARD_F_WAITED_TOO_LONG -2146435065L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNKNOWN_READER
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNKNOWN_READER -2146435063L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_TIMEOUT
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_TIMEOUT -2146435062L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_SHARING_VIOLATION
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_SHARING_VIOLATION -2146435061L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_SMARTCARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_SMARTCARD -2146435060L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNKNOWN_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNKNOWN_CARD -2146435059L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_PROTO_MISMATCH
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_PROTO_MISMATCH -2146435057L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NOT_READY
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NOT_READY -2146435056L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_SYSTEM_CANCELLED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_SYSTEM_CANCELLED -2146435054L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NOT_TRANSACTED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NOT_TRANSACTED -2146435050L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_READER_UNAVAILABLE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_READER_UNAVAILABLE -2146435049L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNSUPPORTED_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNSUPPORTED_CARD -2146434971L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNRESPONSIVE_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNRESPONSIVE_CARD -2146434970L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNPOWERED_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_UNPOWERED_CARD -2146434969L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_RESET_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_RESET_CARD -2146434968L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_REMOVED_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_REMOVED_CARD -2146434967L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_W_INSERTED_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_W_INSERTED_CARD -2146434966L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNSUPPORTED_FEATURE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_UNSUPPORTED_FEATURE -2146435041L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_PCI_TOO_SMALL
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_PCI_TOO_SMALL -2146435047L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_READER_UNSUPPORTED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_READER_UNSUPPORTED -2146435046L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_DUPLICATE_READER
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_DUPLICATE_READER -2146435045L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_CARD_UNSUPPORTED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_CARD_UNSUPPORTED -2146435044L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_SERVICE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_SERVICE -2146435043L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_SERVICE_STOPPED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_SERVICE_STOPPED -2146435042L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_READERS_AVAILABLE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_E_NO_READERS_AVAILABLE -2146435026L
#undef org_poreid_macosx_smartcardio_PCSC_WINDOWS_ERROR_INVALID_HANDLE
#define org_poreid_macosx_smartcardio_PCSC_WINDOWS_ERROR_INVALID_HANDLE 6L
#undef org_poreid_macosx_smartcardio_PCSC_WINDOWS_ERROR_INVALID_PARAMETER
#define org_poreid_macosx_smartcardio_PCSC_WINDOWS_ERROR_INVALID_PARAMETER 87L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_USER
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_USER 0L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_TERMINAL
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_TERMINAL 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_SYSTEM
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_SYSTEM 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_GLOBAL
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SCOPE_GLOBAL 3L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_EXCLUSIVE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_EXCLUSIVE 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_SHARED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_SHARED 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_DIRECT
#define org_poreid_macosx_smartcardio_PCSC_SCARD_SHARE_DIRECT 3L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_LEAVE_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_LEAVE_CARD 0L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_RESET_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_RESET_CARD 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_UNPOWER_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_UNPOWER_CARD 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_EJECT_CARD
#define org_poreid_macosx_smartcardio_PCSC_SCARD_EJECT_CARD 3L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNAWARE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNAWARE 0L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_IGNORE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_IGNORE 1L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_CHANGED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_CHANGED 2L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNKNOWN
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNKNOWN 4L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNAVAILABLE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNAVAILABLE 8L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_EMPTY
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_EMPTY 16L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_PRESENT
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_PRESENT 32L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_ATRMATCH
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_ATRMATCH 64L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_EXCLUSIVE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_EXCLUSIVE 128L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_INUSE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_INUSE 256L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_MUTE
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_MUTE 512L
#undef org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNPOWERED
#define org_poreid_macosx_smartcardio_PCSC_SCARD_STATE_UNPOWERED 1024L
#undef org_poreid_macosx_smartcardio_PCSC_TIMEOUT_INFINITE
#define org_poreid_macosx_smartcardio_PCSC_TIMEOUT_INFINITE -1L
/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardEstablishContext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardEstablishContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardListReaders
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardListReaders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardConnect
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardConnect
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardTransmit
 * Signature: (JI[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardTransmit
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardStatus
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardStatus
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardDisconnect
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardDisconnect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardGetStatusChange
 * Signature: (JJ[I[Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardGetStatusChange
  (JNIEnv *, jclass, jlong, jlong, jintArray, jobjectArray);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardBeginTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardBeginTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardEndTransaction
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardEndTransaction
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_poreid_macosx_smartcardio_PCSC
 * Method:    SCardControl
 * Signature: (JI[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_poreid_macosx_smartcardio_PCSC_SCardControl
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
